In [109]:
import numpy as np 
import pandas as pd

In [110]:
df = pd.read_csv("data/train.csv")

C:\Users\HP\AppData\Local\Temp\ipykernel_21172\1366839329.py:1: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data/train.csv")

In [111]:
df.head()

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,0x1604,CUS_0xd40,March,Aaron Maashoh,-500,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good

In [112]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 28 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   ID                        100000 non-null  object
 1   Customer_ID               100000 non-null  object
 2   Month                     100000 non-null  object
 3   Name                      90015 non-null   object
 4   Age                       100000 non-null  object
 5   SSN                       100000 non-null  object
 6   Occupation                100000 non-null  object
 7   Annual_Income             100000 non-null  object
 8   Monthly_Inhand_Salary     84998 non-null   float64
 9   Num_Bank_Accounts         100000 non-null  int64
 10  Num_Credit_Card           100000 non-null  int64
 11  Interest_Rate             100000 non-null  int64
 12  Num_of_Loan               100000 non-null  object
 13  Type_of_Loan              88592 non-null   object
 14  Delay_from_due_date       100000 non-null  int64
 15  Num_of_Delayed_Payment    92998 non-null   object
 16  Changed_Credit_Limit      100000 non-null  object
 17  Num_Credit_Inquiries      98035 non-null   float64
 18  Credit_Mix                100000 non-null  object
 19  Outstanding_Debt          100000 non-null  object
 20  Credit_Utilization_Ratio  100000 non-null  float64
 21  Credit_History_Age        90970 non-null   object
 22  Payment_of_Min_Amount     100000 non-null  object
 23  Total_EMI_per_month       100000 non-null  float64
 24  Amount_invested_monthly   95521 non-null   object
 25  Payment_Behaviour         100000 non-null  object
 26  Monthly_Balance           98800 non-null   object
 27  Credit_Score              100000 non-null  object
dtypes: float64(4), int64(4), object(20)
memory usage: 21.4+ MB
None

In [113]:
print(df.isnull().sum())

ID                              0
Customer_ID                     0
Month                           0
Name                         9985
Age                             0
SSN                             0
Occupation                      0
Annual_Income                   0
Monthly_Inhand_Salary       15002
Num_Bank_Accounts               0
Num_Credit_Card                 0
Interest_Rate                   0
Num_of_Loan                     0
Type_of_Loan                11408
Delay_from_due_date             0
Num_of_Delayed_Payment       7002
Changed_Credit_Limit            0
Num_Credit_Inquiries         1965
Credit_Mix                      0
Outstanding_Debt                0
Credit_Utilization_Ratio        0
Credit_History_Age           9030
Payment_of_Min_Amount           0
Total_EMI_per_month             0
Amount_invested_monthly      4479
Payment_Behaviour               0
Monthly_Balance              1200
Credit_Score                    0
dtype: int64

In [114]:
df.Monthly_Inhand_Salary = df.Monthly_Inhand_Salary.fillna(df.Monthly_Inhand_Salary.mean())

In [115]:
df['Num_of_Delayed_Payment'] = pd.to_numeric(df['Num_of_Delayed_Payment'], errors='coerce').astype('Int64')

In [116]:
df.Num_of_Delayed_Payment = df.Num_of_Delayed_Payment.fillna(df.Num_of_Delayed_Payment.mean().astype(int))

In [117]:
df.Num_Credit_Inquiries = df.Num_Credit_Inquiries.fillna(df.Num_Credit_Inquiries.mean())

In [118]:
df.Credit_History_Age

0         22 Years and 1 Months
1                           NaN
2         22 Years and 3 Months
3         22 Years and 4 Months
4         22 Years and 5 Months
                  ...
99995     31 Years and 6 Months
99996     31 Years and 7 Months
99997     31 Years and 8 Months
99998     31 Years and 9 Months
99999    31 Years and 10 Months
Name: Credit_History_Age, Length: 100000, dtype: object

In [119]:
def convert_to_months(value):
    if pd.isna(value):
        return np.nan
    parts = value.split(' ')
    years = int(parts[0])
    months = int(parts[3])
    total_months = years * 12 + months
    return total_months

In [120]:
df['Credit_History_Age_Months'] = df['Credit_History_Age'].apply(convert_to_months)

In [121]:
df['Credit_History_Age_Months']

0        265.0
1          NaN
2        267.0
3        268.0
4        269.0
         ...
99995    378.0
99996    379.0
99997    380.0
99998    381.0
99999    382.0
Name: Credit_History_Age_Months, Length: 100000, dtype: float64

In [122]:
df['Credit_History_Age_Months'] = df['Credit_History_Age_Months'].fillna(df['Credit_History_Age_Months'].mean())

In [123]:
df.Amount_invested_monthly = pd.to_numeric(df.Amount_invested_monthly,errors ='coerce').astype('float64')

In [124]:
df.Amount_invested_monthly = df.Amount_invested_monthly.fillna(df.Amount_invested_monthly.mean())

In [125]:
df.Monthly_Balance = pd.to_numeric(df.Monthly_Balance,errors ='coerce').astype('float64')

In [126]:
df.Monthly_Balance = df.Monthly_Balance.fillna(df.Monthly_Balance.mean())

In [127]:
print(df.isnull().sum())

ID                               0
Customer_ID                      0
Month                            0
Name                          9985
Age                              0
SSN                              0
Occupation                       0
Annual_Income                    0
Monthly_Inhand_Salary            0
Num_Bank_Accounts                0
Num_Credit_Card                  0
Interest_Rate                    0
Num_of_Loan                      0
Type_of_Loan                 11408
Delay_from_due_date              0
Num_of_Delayed_Payment           0
Changed_Credit_Limit             0
Num_Credit_Inquiries             0
Credit_Mix                       0
Outstanding_Debt                 0
Credit_Utilization_Ratio         0
Credit_History_Age            9030
Payment_of_Min_Amount            0
Total_EMI_per_month              0
Amount_invested_monthly          0
Payment_Behaviour                0
Monthly_Balance                  0
Credit_Score                     0
Credit_History_Age_Months        0
dtype: int64

In [128]:
unused_columns = ['ID','Customer_ID','Month','Name','SSN','Type_of_Loan','Credit_History_Age','Payment_of_Min_Amount','Payment_Behaviour']

In [129]:
df1=df.drop(unused_columns,axis=1)

In [130]:
print(df1.isnull().sum())

Age                          0
Occupation                   0
Annual_Income                0
Monthly_Inhand_Salary        0
Num_Bank_Accounts            0
Num_Credit_Card              0
Interest_Rate                0
Num_of_Loan                  0
Delay_from_due_date          0
Num_of_Delayed_Payment       0
Changed_Credit_Limit         0
Num_Credit_Inquiries         0
Credit_Mix                   0
Outstanding_Debt             0
Credit_Utilization_Ratio     0
Total_EMI_per_month          0
Amount_invested_monthly      0
Monthly_Balance              0
Credit_Score                 0
Credit_History_Age_Months    0
dtype: int64

In [131]:
df1.shape

(100000, 20)

In [132]:
df1.dtypes

Age                           object
Occupation                    object
Annual_Income                 object
Monthly_Inhand_Salary        float64
Num_Bank_Accounts              int64
Num_Credit_Card                int64
Interest_Rate                  int64
Num_of_Loan                   object
Delay_from_due_date            int64
Num_of_Delayed_Payment         Int64
Changed_Credit_Limit          object
Num_Credit_Inquiries         float64
Credit_Mix                    object
Outstanding_Debt              object
Credit_Utilization_Ratio     float64
Total_EMI_per_month          float64
Amount_invested_monthly      float64
Monthly_Balance              float64
Credit_Score                  object
Credit_History_Age_Months    float64
dtype: object

In [133]:
df1.head()

,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,Num_Credit_Inquiries,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Total_EMI_per_month,Amount_invested_monthly,Monthly_Balance,Credit_Score,Credit_History_Age_Months
0,23,Scientist,19114.12,1824.843333,3,4,3,4,3,7,11.27,4.0,_,809.98,26.822620,49.574949,80.415295,312.494089,Good,265.000000
1,23,Scientist,19114.12,4194.170850,3,4,3,4,-1,31,11.27,4.0,Good,809.98,31.944960,49.574949,118.280222,284.629162,Good,221.195405
2,-500,Scientist,19114.12,4194.170850,3,4,3,4,3,7,_,4.0,Good,809.98,28.609352,49.574949,81.699521,331.209863,Good,267.000000
3,23,Scientist,19114.12,4194.170850,3,4,3,4,5,4,6.27,4.0,Good,809.98,31.377862,49.574949,199.458074,223.451310,Good,268.000000
4,23,Scientist,19114.12,1824.843333,3,4,3,4,6,31,11.27,4.0,Good,809.98,24.797347,49.574949,41.420153,341.489231,Good,269.000000

In [134]:
cat_to_num=['Age','Annual_Income','Num_of_Loan','Changed_Credit_Limit','Credit_Mix','Outstanding_Debt','Payment_of_Min_Amount','Payment_Behaviour']

In [135]:
print(df1.isnull().sum())

Age                          0
Occupation                   0
Annual_Income                0
Monthly_Inhand_Salary        0
Num_Bank_Accounts            0
Num_Credit_Card              0
Interest_Rate                0
Num_of_Loan                  0
Delay_from_due_date          0
Num_of_Delayed_Payment       0
Changed_Credit_Limit         0
Num_Credit_Inquiries         0
Credit_Mix                   0
Outstanding_Debt             0
Credit_Utilization_Ratio     0
Total_EMI_per_month          0
Amount_invested_monthly      0
Monthly_Balance              0
Credit_Score                 0
Credit_History_Age_Months    0
dtype: int64

In [136]:
df1.dtypes

Age                           object
Occupation                    object
Annual_Income                 object
Monthly_Inhand_Salary        float64
Num_Bank_Accounts              int64
Num_Credit_Card                int64
Interest_Rate                  int64
Num_of_Loan                   object
Delay_from_due_date            int64
Num_of_Delayed_Payment         Int64
Changed_Credit_Limit          object
Num_Credit_Inquiries         float64
Credit_Mix                    object
Outstanding_Debt              object
Credit_Utilization_Ratio     float64
Total_EMI_per_month          float64
Amount_invested_monthly      float64
Monthly_Balance              float64
Credit_Score                  object
Credit_History_Age_Months    float64
dtype: object

In [137]:
df1.Age = pd.to_numeric(df1.Age,errors ='coerce').astype('float64')
df1.Annual_Income = pd.to_numeric(df1.Annual_Income,errors ='coerce').astype('float64')
df1.Num_of_Loan = pd.to_numeric(df1.Num_of_Loan,errors ='coerce').astype('float64')
df1.Changed_Credit_Limit = pd.to_numeric(df1.Changed_Credit_Limit,errors ='coerce').astype('float64')
df1.Outstanding_Debt = pd.to_numeric(df1.Outstanding_Debt,errors ='coerce').astype('float64')

In [138]:
df2 = df1.dropna()

In [139]:
df2.shape

(81564, 20)

In [140]:
df2.Credit_Score.unique()

array(['Good', 'Standard', 'Poor'], dtype=object)

In [141]:
df2["Credit_Score"] = df2["Credit_Score"].map({"Standard": 1, 
                               "Good": 2, 
                               "Poor": 0})

C:\Users\HP\AppData\Local\Temp\ipykernel_21172\3973453474.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Credit_Score"] = df2["Credit_Score"].map({"Standard": 1,

In [142]:
X=df2.drop('Credit_Score',axis = 1)
y=df2['Credit_Score']

In [143]:
num_features = X.select_dtypes(exclude="object").columns
cat_features = X.select_dtypes(include="object").columns

In [144]:
num_features

Index(['Age', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts',
       'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan',
       'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit',
       'Num_Credit_Inquiries', 'Outstanding_Debt', 'Credit_Utilization_Ratio',
       'Total_EMI_per_month', 'Amount_invested_monthly', 'Monthly_Balance',
       'Credit_History_Age_Months'],
      dtype='object')

In [145]:
cat_features

Index(['Occupation', 'Credit_Mix'], dtype='object')

In [146]:
X = pd.get_dummies(X,columns=cat_features,dtype='int')

In [147]:
X.dtypes
import json
columns = {
    'data_columns': [col.lower() for col in X.columns]
}
with open ('columns.json','w') as f:
    f.write(json.dumps(columns))

In [148]:
num_features = X.columns

In [149]:
len(num_features)

37

In [150]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
#oh_transformer = OneHotEncoder()


preprocessor = ColumnTransformer(
    [
        #("OneHotEncoder", oh_transformer, cat_features),
         ("StandardScaler", numeric_transformer, num_features),        
    ]
)

In [151]:
#X = preprocessor.fit_transform(X)

In [152]:
X.shape

(81564, 37)

In [153]:
# separate dataset into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape, X_test.shape

((65251, 37), (16313, 37))

In [154]:
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [155]:
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [156]:
"""
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

models = {
    "Logistic Regression": LogisticRegression(),
    "K-Neighbors Classifier": KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest Classifier": RandomForestClassifier(),
    "XGBClassifier": XGBClassifier(),
    #"CatBoost Classifier": CatBoostClassifier(verbose=False),
    "AdaBoost Classifier": AdaBoostClassifier(),
    "Gradient Boosting Classifier": GradientBoostingClassifier(),
    "Support Vector Classifier": SVC()
}

model_list = []
accuracy_list = []
precision_list = []
recall_list = []
f1_list = []

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train)  # Train model

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    
    # Evaluate Train and Test dataset
    train_accuracy = accuracy_score(y_train, y_train_pred)
    train_precision = precision_score(y_train, y_train_pred, average='weighted')
    train_recall = recall_score(y_train, y_train_pred, average='weighted')
    train_f1 = f1_score(y_train, y_train_pred, average='weighted')

    test_accuracy = accuracy_score(y_test, y_test_pred)
    test_precision = precision_score(y_test, y_test_pred, average='weighted')
    test_recall = recall_score(y_test, y_test_pred, average='weighted')
    test_f1 = f1_score(y_test, y_test_pred, average='weighted')

    model_name = list(models.keys())[i]
    model_list.append(model_name)
    
    print(model_name)
    
    print('Model performance for Training set')
    print("- Accuracy: {:.4f}".format(train_accuracy))
    print("- Precision: {:.4f}".format(train_precision))
    print("- Recall: {:.4f}".format(train_recall))
    print("- F1 Score: {:.4f}".format(train_f1))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Accuracy: {:.4f}".format(test_accuracy))
    print("- Precision: {:.4f}".format(test_precision))
    print("- Recall: {:.4f}".format(test_recall))
    print("- F1 Score: {:.4f}".format(test_f1))

    accuracy_list.append(test_accuracy)
    precision_list.append(test_precision)
    recall_list.append(test_recall)
    f1_list.append(test_f1)
    
    print('='*35)
    print('\n')
"""

'\nfrom sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score\n\nmodels = {\n    "Logistic Regression": LogisticRegression(),\n    "K-Neighbors Classifier": KNeighborsClassifier(),\n    "Decision Tree": DecisionTreeClassifier(),\n    "Random Forest Classifier": RandomForestClassifier(),\n    "XGBClassifier": XGBClassifier(),\n    #"CatBoost Classifier": CatBoostClassifier(verbose=False),\n    "AdaBoost Classifier": AdaBoostClassifier(),\n    "Gradient Boosting Classifier": GradientBoostingClassifier(),\n    "Support Vector Classifier": SVC()\n}\n\nmodel_list = []\naccuracy_list = []\nprecision_list = []\nrecall_list = []\nf1_list = []\n\nfor i in range(len(list(models))):\n    model = list(models.values())[i]\n    model.fit(X_train, y_train)  # Train model\n\n    # Make predictions\n    y_train_pred = model.predict(X_train)\n    y_test_pred = model.predict(X_test)\n    \n    # Evaluate Train and Test dataset\n    train_accuracy = accuracy_score(y_train, y_train_pred)\n    train_precision = precision_score(y_train, y_train_pred, average=\'weighted\')\n    train_recall = recall_score(y_train, y_train_pred, average=\'weighted\')\n    train_f1 = f1_score(y_train, y_train_pred, average=\'weighted\')\n\n    test_accuracy = accuracy_score(y_test, y_test_pred)\n    test_precision = precision_score(y_test, y_test_pred, average=\'weighted\')\n    test_recall = recall_score(y_test, y_test_pred, average=\'weighted\')\n    test_f1 = f1_score(y_test, y_test_pred, average=\'weighted\')\n\n    model_name = list(models.keys())[i]\n    model_list.append(model_name)\n    \n    print(model_name)\n    \n    print(\'Model performance for Training set\')\n    print("- Accuracy: {:.4f}".format(train_accuracy))\n    print("- Precision: {:.4f}".format(train_precision))\n    print("- Recall: {:.4f}".format(train_recall))\n    print("- F1 Score: {:.4f}".format(train_f1))\n\n    print(\'----------------------------------\')\n    \n    print(\'Model performance for Test set\')\n    print("- Accuracy: {:.4f}".format(test_accuracy))\n    print("- Precision: {:.4f}".format(test_precision))\n    print("- Recall: {:.4f}".format(test_recall))\n    print("- F1 Score: {:.4f}".format(test_f1))\n\n    accuracy_list.append(test_accuracy)\n    precision_list.append(test_precision)\n    recall_list.append(test_recall)\n    f1_list.append(test_f1)\n    \n    print(\'=\'*35)\n    print(\'\n\')\n'

In [157]:
model = XGBClassifier()
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.7449886593514375

In [158]:
import pickle
with open('credit_ccore_classifier_model.pickle','wb') as f:
    pickle.dump(model,f)

In [159]:
with open('preprocessor.pickle','wb') as f:
    pickle.dump(preprocessor,f)

In [163]:
model.predict(X_test)[:5]

array([1, 1, 2, 1, 0], dtype=int64)

In [164]:
y_test[:5]

6128     1
10507    1
85748    2
43857    1
37267    0
Name: Credit_Score, dtype: int64

       Age  Annual_Income  Monthly_Inhand_Salary  Num_Bank_Accounts  \
6128  31.0       79837.02               6414.085                  2

      Num_Credit_Card  Interest_Rate  Num_of_Loan  Delay_from_due_date  \
6128                7             10          1.0                   14

      Num_of_Delayed_Payment  Changed_Credit_Limit  ...  \
6128                       4                  8.72  ...

      Occupation_Media_Manager  Occupation_Musician  Occupation_Scientist  \
6128                         0                    0                     0

      Occupation_Teacher  Occupation_Writer  Occupation________  \
6128                   0                  0                   0

      Credit_Mix_Bad  Credit_Mix_Good  Credit_Mix_Standard  Credit_Mix__
6128               0                1                    0             0

[1 rows x 37 columns]